spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopingMall
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create # 운영시 절대 create, create-drop, update 사용하면 안됨 / 개발초기 create, update / 테스트 서버 update, validate / 스테이징,운영 validate, none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace