### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "임동희",
  "age": 99,
  "phoneNumber": "010-1234-5678",
  "email": "ldh7043@gmail.com",
  "password": "1234",
  "address": {
    "city": "서울",
    "street": "잠실",
    "zipcode": "01010"
  }
}

### 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "ldh7043@gmail.com",
  "password": "1234"
}

### 메인페이지
GET http://localhost:8080